name: Build

on:
  workflow_dispatch:
#  push:
#    paths: [ '.github/workflows/build.yml','.github/workflows/buildluna.yml','src/**']
#  pull_request:
#    paths: [ '.github/workflows/build.yml','.github/workflows/buildluna.yml','src/**']

jobs:
  buildluna:
    uses: ./.github/workflows/buildluna.yml
  